apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: techtrends-prod
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      valueFiles:
      - helm/values-prod.yaml 
    path: helm
    repoURL: https://github.com/phanhoaithuabc/blog-web-docker-githubaction-helm-k8s-argocd.git
    targetRevision: HEAD
  syncPolicy: {}